"""Initial migration

Revision ID: 1bc806159813
Revises: 
Create Date: 2025-03-27 07:55:53.441207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc806159813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('test_result')
    op.drop_table('practice_session')
    op.drop_table('teacher')
    op.drop_table('session_students')
    with op.batch_alter_table('lab_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=10), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('max_students',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('min_students')

    with op.batch_alter_table('session_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registered_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('register_time')
        batch_op.drop_column('status')
        batch_op.drop_column('check_in_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('register_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('registered_at')
        batch_op.drop_column('attendance_status')

    with op.batch_alter_table('lab_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_students', sa.INTEGER(), nullable=True))
        batch_op.alter_column('max_students',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('verification_code')
        batch_op.drop_column('date')

    op.create_table('session_students',
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['practice_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'student_id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('practice_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('practice_session_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
